# Generated by Django 4.2.16 on 2026-08-16 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_vulnerabilitymaster_studentvulnerability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('section_id', models.IntegerField(default=1)),
                ('term', models.CharField(max_length=20)),
                ('assessment_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assessment',
            },
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('assessment_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('duration_months', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'assessment_type',
            },
        ),
        migrations.CreateModel(
            name='LearningBehaviourOption',
            fields=[
                ('behaviour_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'learning_behaviour_option',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('class_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='StudentObservation',
            fields=[
                ('observation_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_improvements', models.TextField(blank=True, null=True)),
                ('subjects_needing_support', models.TextField(blank=True, null=True)),
                ('intervention_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='school.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='school.student')),
            ],
            options={
                'db_table': 'student_observation',
            },
        ),
        migrations.CreateModel(
            name='StudentLearningBehaviour',
            fields=[
                ('behaviour_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_behaviours', to='school.assessment')),
                ('behaviour_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.learningbehaviouroption')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_behaviours', to='school.student')),
            ],
            options={
                'db_table': 'student_learning_behaviour',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticOption',
            fields=[
                ('diagnostic_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('understanding_level', 'Understanding Level'), ('application_ability', 'Application Ability'), ('interest_level', 'Interest Level')], max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'diagnostic_option',
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='school.assessment')),
            ],
            options={
                'db_table': 'assessment_submission',
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='school.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='school.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='school.subject')),
            ],
            options={
                'db_table': 'assessment_score',
            },
        ),
        migrations.CreateModel(
            name='AssessmentDiagnostic',
            fields=[
                ('diagnostic_id', models.AutoField(primary_key=True, serialize=False)),
                ('understanding_level', models.CharField(blank=True, max_length=50, null=True)),
                ('application_ability', models.CharField(blank=True, max_length=50, null=True)),
                ('interest_level', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='school.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_diagnostics', to='school.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_diagnostics', to='school.subject')),
            ],
            options={
                'db_table': 'assessment_diagnostic',
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='school.assessmenttype'),
        ),
    ]
