# Generated by Django 6.0.7 on 2026-09-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
