from django.urls import path

from school.views.assessment import (
    AssessmentBehaviourView,
    AssessmentCreateView,
    AssessmentDetailView,
    AssessmentDetailsView,
    AssessmentDiagnosticBulkView,
    AssessmentDiagnosticListView,
    AssessmentScoreBulkView,
    AssessmentStatisticsView,
    AssessmentSubmitView,
    AssessmentTypeListView,
    ComparisonView,
    DiagnosticOptionsView,
    LearningBehaviourOptionListView,
    StudentComparisonView,
    StudentDashboardView,
    StudentObservationView,
    StudentPerformanceTrendView,
    SubjectComparisonView,
    SubjectListView,
    AssessmentObservationListView,
)
from school.views.metadata import (
    AssessmentTypeMetadataDetailView,
    AssessmentTypeMetadataListCreateView,
    DiagnosticOptionMetadataDetailView,
    DiagnosticOptionMetadataListCreateView,
    LearningBehaviourOptionMetadataDetailView,
    LearningBehaviourOptionMetadataListCreateView,
    SubjectMetadataDetailView,
    SubjectMetadataListCreateView,
)

urlpatterns = [
    path('assessment-types/', AssessmentTypeListView.as_view(), name='assessment-types'),
    path('subjects/', SubjectListView.as_view(), name='subjects'),
    path('metadata/assessment-types/', AssessmentTypeMetadataListCreateView.as_view(), name='metadata-assessment-types-list-create'),
    path('metadata/assessment-types/<int:pk>/', AssessmentTypeMetadataDetailView.as_view(), name='metadata-assessment-types-detail'),
    path('metadata/subjects/', SubjectMetadataListCreateView.as_view(), name='metadata-subjects-list-create'),
    path('metadata/subjects/<int:pk>/', SubjectMetadataDetailView.as_view(), name='metadata-subjects-detail'),
    path('metadata/diagnostic-options/', DiagnosticOptionMetadataListCreateView.as_view(), name='metadata-diagnostic-options-list-create'),
    path('metadata/diagnostic-options/<int:pk>/', DiagnosticOptionMetadataDetailView.as_view(), name='metadata-diagnostic-options-detail'),
    path('metadata/learning-behaviours/', LearningBehaviourOptionMetadataListCreateView.as_view(), name='metadata-learning-behaviours-list-create'),
    path('metadata/learning-behaviours/<int:pk>/', LearningBehaviourOptionMetadataDetailView.as_view(), name='metadata-learning-behaviours-detail'),
    path('assessments/', AssessmentCreateView.as_view(), name='assessments-create'),
    path('assessments/<int:assessment_id>/', AssessmentDetailView.as_view(), name='assessment-detail'),
    path('assessments/<int:assessment_id>/scores/', AssessmentScoreBulkView.as_view(), name='assessment-scores'),
    path('assessments/<int:assessment_id>/scores/bulk', AssessmentScoreBulkView.as_view(), name='assessment-scores-bulk'),
    path('assessments/<int:assessment_id>/diagnostics/', AssessmentDiagnosticListView.as_view(), name='assessment-diagnostics'),
    path('assessments/<int:assessment_id>/diagnostics/bulk', AssessmentDiagnosticBulkView.as_view(), name='assessment-diagnostics-bulk'),
    path('diagnostic-options/', DiagnosticOptionsView.as_view(), name='diagnostic-options'),
    path('learning-behaviours/', LearningBehaviourOptionListView.as_view(), name='learning-behaviours'),
    path('assessments/<int:assessment_id>/behaviours/', AssessmentBehaviourView.as_view(), name='assessment-behaviours'),
    path('assessments/<int:assessment_id>/behaviours/bulk', AssessmentBehaviourView.as_view(), name='assessment-behaviours-bulk'),
    path('assessments/<int:assessment_id>/observations/', AssessmentObservationListView.as_view(), name='assessment-observations'),
    path('assessments/<int:assessment_id>/students/<int:student_id>/observation', StudentObservationView.as_view(), name='student-observation'),
    path('assessments/<int:assessment_id>/submit', AssessmentSubmitView.as_view(), name='assessment-submit'),
    path('assessments/<int:assessment_id>/comparison', ComparisonView.as_view(), name='assessment-comparison'),
    path('assessments/<int:assessment_id>/comparison/subjects', SubjectComparisonView.as_view(), name='assessment-subject-comparison'),
    path('assessments/<int:assessment_id>/comparison/students', StudentComparisonView.as_view(), name='assessment-student-comparison'),
    path('students/<int:student_id>/performance/trends', StudentPerformanceTrendView.as_view(), name='student-performance-trend'),
    path('assessments/<int:assessment_id>/statistics', AssessmentStatisticsView.as_view(), name='assessment-statistics'),
    path('students/<int:student_id>/dashboard', StudentDashboardView.as_view(), name='student-dashboard'),
    path('assessments/<int:assessment_id>/details', AssessmentDetailsView.as_view(), name='assessment-details'),
]
