from .attendance import AttendanceCreateView, AttendanceListView
from .assessment import (
    AssessmentBehaviourView,
    AssessmentCreateView,
    AssessmentDetailView,
    AssessmentDetailsView,
    AssessmentDiagnosticBulkView,
    AssessmentDiagnosticListView,
    AssessmentScoreBulkView,
    AssessmentStatisticsView,
    AssessmentSubmitView,
    AssessmentTypeListView,
    ComparisonView,
    DiagnosticOptionsView,
    LearningBehaviourOptionListView,
    StudentComparisonView,
    StudentDashboardView,
    StudentObservationView,
    StudentPerformanceTrendView,
    SubjectComparisonView,
    SubjectListView,
)
from .metadata import (
    AssessmentTypeMetadataDetailView,
    AssessmentTypeMetadataListCreateView,
    DiagnosticOptionMetadataDetailView,
    DiagnosticOptionMetadataListCreateView,
    LearningBehaviourOptionMetadataDetailView,
    LearningBehaviourOptionMetadataListCreateView,
    SubjectMetadataDetailView,
    SubjectMetadataListCreateView,
)
from .student import StudentListView, StudentRetrieveUpdateDestroyView

__all__ = [
    'AttendanceCreateView',
    'AttendanceListView',
    'StudentListView',
    'StudentRetrieveUpdateDestroyView',
    'AssessmentTypeListView',
    'SubjectListView',
    'AssessmentCreateView',
    'AssessmentDetailView',
    'AssessmentScoreBulkView',
    'AssessmentDiagnosticListView',
    'AssessmentDiagnosticBulkView',
    'DiagnosticOptionsView',
    'LearningBehaviourOptionListView',
    'AssessmentBehaviourView',
    'StudentObservationView',
    'AssessmentSubmitView',
    'ComparisonView',
    'SubjectComparisonView',
    'StudentComparisonView',
    'StudentPerformanceTrendView',
    'AssessmentStatisticsView',
    'StudentDashboardView',
    'AssessmentDetailsView',
    'AssessmentTypeMetadataListCreateView',
    'AssessmentTypeMetadataDetailView',
    'SubjectMetadataListCreateView',
    'SubjectMetadataDetailView',
    'DiagnosticOptionMetadataListCreateView',
    'DiagnosticOptionMetadataDetailView',
    'LearningBehaviourOptionMetadataListCreateView',
    'LearningBehaviourOptionMetadataDetailView',
]
